# Podfile
# Flutter iOS Podfile - Syncfusion PDF Viewer and Device Info Plus support

# CocoaPods analysis end date
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

platform :ios, '12.0'

# CocoaPods will not download any pods
target 'Runner' do
  pod 'Flutter', :path => 'Flutter'

  # Packages
  pod 'device_info_plus', :path => '.symlinks/plugins/device_info_plus/ios'
  pod 'syncfusion_flutter_pdfviewer', :path => '.symlinks/plugins/syncfusion_flutter_pdfviewer/ios'
  pod 'flutter_secure_storage', :path => '.symlinks/plugins/flutter_secure_storage/ios'
  pod 'shared_preferences_ios', :path => '.symlinks/plugins/shared_preferences_ios/ios'
  pod 'sqflite', :path => '.symlinks/plugins/sqflite/ios'
  pod 'url_launcher_ios', :path => '.symlinks/plugins/url_launcher_ios/ios'
  pod 'webview_flutter_wkwebview', :path => '.symlinks/plugins/webview_flutter_wkwebview/ios'
  pod 'google_sign_in_ios', :path => '.symlinks/plugins/google_sign_in_ios/ios'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'PERMISSION_CAMERA=1',
        ]
      end
    end
  end
end

# Project-wide properties
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Ensure minimum deployment target is 12.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
